baseURL       = "https://robinbaudnws.netlify.app"
languageCode  = "fr-FR"
title         = "RobinBaud game designer"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Accueil"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "À propos"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "À propos"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Contact"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/poly.jpg"
    heading               = "game designer"
    tagline               = "Robin Baud"
    primary_button        = "See Our Works"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "Mes Récents Travaux"
    subtitle  = "s'exercer par la pratique"
  [params.call_to_action]
    enable              = true
    background_image    = "images/background/gamingroom2.jpg"
    title               = "DEVELLOPONS ENSEMBLE"
    primary_button      = "Laissez un message"
    primary_button_url  = "contact"
    secondary_button    = "Pas convaincu ?"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Me contacter"
      address = "32 rue de l'aqueduc 27930 Le Vieil-Evreux"
      phone   = "06 71 41 79 53"
      email   = "robinbaud@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Plan du site"
        
        [[params.footer.sitemap.link]]
          name = "Portfolio"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = " propos"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Réseaux"
        [[params.footer.social.link]]
          name = "Linkedin"
          url  = "https://www.linkedin.com/in/baud-robin-7b618818b/"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "https://www.instagram.com/robin.baud/"
        [[params.footer.social.link]]
          name = "Youtube"
          url  = "https://www.youtube.com/channel/UC92WJgIrdYnk-pt7ai9L6Hw"